@startuml
class com.example.eventparticipation.CreateEventActivityTest {
+ ActivityScenarioRule<CreateEventActivity> activityRule
+ void setUp()
+ void tearDown()
+ void testCreateEventWithAllVariables()
+ void testCreateEventWithRequiredFields()
+ void testSetRegistrationPeriod()
+ void testToggleGeolocationRequirement()
+ void testOptionalWaitlistLimit()
- void clickTomorrow()
}


class com.example.eventparticipation.EntrantDashboardActivityTest {
+ void activityLaunches_reachesResumedState()
+ void activityInstance_isNotNull()
+ void activityRecreated_doesNotCrash()
+ void activityPausedThenResumed_isResumed()
+ void activityMovedToCreated_doesNotCrash()
}

class com.example.eventparticipation.EntrantNotificationsActivityTest {
+ void selectedNotification_showsInvitationActions()
+ void acceptInvitation_updatesCardState()
+ void notSelectedNotification_hasNoInvitationButton()
- Intent makeIntent(NotificationItem)
- NotificationItem makeSelectedNotification()
- NotificationItem makeNotSelectedNotification()
}

class com.example.eventparticipation.ManageEventActivityUpdatePosterTest {
- {static} String EVENT_ID
- {static} String ORG_ID
+ void setUp()
+ void updatePosterButton_isEnabled_whenPosterAlreadyExists()
}


class com.example.eventparticipation.ManageEventActivityIntentTest {
+ void setUp()
+ void tearDown()
+ void clickingViewEntrants_launchesEntrantListActivity()
+ void clickingViewMap_launchesWaitlistMapActivity()
- Intent validIntent()
}

class com.example.eventparticipation.ProfileActivityTest {
- {static} String TEST_ENTRANT_ID
- {static} String TEST_EVENT_1
- {static} String TEST_EVENT_2
- FirebaseFirestore db
+ void setUp()
- void waitForProfileLoad()
- String getText(TextInputEditText)
- void invokePrivateMethod(ProfileActivity,String)
- ActivityScenario<ProfileActivity> launchProfileActivity()
- DocumentSnapshot waitForDocumentState(DocumentReference,boolean)
+ void profileScreen_displaysMainViews()
+ void saveProfile_emptyName_showsNameError()
+ void saveProfile_emptyEmail_showsEmailError()
+ void saveProfile_invalidEmail_showsEmailError()
+ void saveProfile_invalidPhone_showsPhoneError()
+ void saveProfile_validInput_writesProfileDocument()
+ void deleteAccount_removesProfileAndWaitingListEntries()
}


class com.example.eventparticipation.EntrantEventDetailActivityTest {
- Intent makeTestIntent()
+ void activityLaunchesWithValidExtras_reachesResumed()
+ void activityInstance_isNotNull()
+ void activityRecreated_doesNotCrash()
+ void missingEventId_doesNotCrash()
+ void launchWithWaitingAndEnrolledCounts_doesNotCrash()
+ void activityPausedThenResumed_isResumed()
}

class com.example.eventparticipation.EntrantListActivityTest {
- {static} String TEST_ORG_ID
- {static} String TEST_EVENT_ID
+ void setUp()
+ void searchEntrantsByEmail_showsOnlyMatchingEntrant()
}


class com.example.eventparticipation.ManageEventActivityUploadPosterTest {
- {static} String EVENT_ID
- {static} String ORG_ID
+ void setUp()
+ void uploadPosterButton_isDisabled_whenPosterAlreadyExists()
}


class com.example.eventparticipation.WaitlistMapActivityTest {
+ void launchWithValidEventId_showsToolbar()
- Intent validIntent()
}

class com.example.eventparticipation.ExampleInstrumentedTest {
+ void useAppContext()
}

class com.example.eventparticipation.WaitlistMapActivityIntentTest {
+ void missingOrganizerId_activityStillLaunches()
+ void missingEventId_destroysActivity()
}

class com.example.eventparticipation.OrganizerDashboardIntentTest {
+ void setUp()
+ void tearDown()
+ void clickingManage_launchesManageEventActivity_withCorrectExtras()
+ void clickingEntrants_launchesEntrantListActivity_withCorrectExtras()
- List<Event> getEventList(OrganizerDashboardActivity)
- void invokeSetupRecyclerView(OrganizerDashboardActivity)
- OnEventClickListener getAdapterListener(OrganizerDashboardActivity)
}

class com.example.eventparticipation.SelectRoleActivityTest {
+ void activityLaunches_reachesResumedState()
+ void activityLaunches_isNotDestroyed()
+ void activityLaunchedTwice_doesNotCrash()
+ void activityRecreated_doesNotCrash()
+ void activityMovedToBackground_reachesStartedState()
+ void activityMovedToCreated_reachesCreatedState()
+ void activityInstance_isAccessible()
+ void activityPausedThenResumed_isResumed()
}

class com.example.eventparticipation.EntrantListActivityIntentTest {
+ void missingEventId_finishesActivity()
+ void missingOrganizerId_finishesActivity()
}

class com.example.eventparticipation.QRCodeScannerTest {
+ void launchEventDetailActivity_withEventId()
+ void activityReceivesEventId()
}

class com.example.eventparticipation.ProfileInitializerFirestoreTest {
- FirebaseFirestore db
- ProfileInitializer initializer
+ void setUp()
+ void ensureEntrantProfileExists_createsBlankProfile_whenProfileDoesNotExist()
+ void ensureEntrantProfileExists_doesNotOverwriteExistingProfile()
+ void ensureOrganizerProfileExists_createsBlankProfile_whenProfileDoesNotExist()
+ void ensureAdminProfileExists_createsBlankProfile_whenProfileDoesNotExist()
- String uniqueId(String)
- void setDocument(String,String,Map<String,Object>)
- void deleteDocument(String,String)
- DocumentSnapshot getDocument(String,String)
}


class com.example.eventparticipation.ManageEventActivityLotteryTest {
- {static} String EVENT_ID
- {static} String ORG_ID
+ void setUp()
+ void testRunLotteryDialogAppears()
+ void testRunLotteryDialog_WithInput()
+ void testDrawReplacementButtonExists()
}


@enduml